name: Backend Pipeline

on:
  push:
    branches:
      - Application_1
      - Application_2
      - Application_3

jobs: 
  
  Application_1_build:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Application_1

      - run: echo "Running Application_1_build"

  Application_2_bulid:

    runs-on: ubuntu-latest
    steps:
      - name : Application_2
      - run : echo "running Application_2_bulid"

  Application_3_bulid:

    runs-on: ubuntu-latest
    steps:
      - name : Application_3
      - run : echo "running Application_3_bulid"

  # lint:

  #   runs-on: ubuntu-latest

  #   steps:

  #     - name: Checkout Application
  #       uses: actions/checkout@v4

  #     - name: Waiting for 5 sec
  #       run: sleep 5 

  #     - run: echo "Running lint"

  # test:

  #   needs: [build, lint]

  #   runs-on: ubuntu-latest
    
  #   steps:
      
  #     - name: Checkout Application
  #       uses: actions/checkout@v4

  #     - run: echo "Running lint"

  # deploy:

  #   needs: test

  #   runs-on: ubuntu-latest

  #   steps:

  #     - name: Checkout Application
  #       uses: actions/checkout@v4

  #     - run: echo "Running lint"

